---
- name: Работа с БД
  vars:
    db_env: "{{ dev_mysql | items2dict(key_name='name', value_name='value') }}"
  ansible.builtin.include_tasks:
    file: "../services/db.yml"

- name: Работа с файлами магазина
  ansible.builtin.include_tasks:
    file: "../services/files.yml"
