galaxy_info:
  author: Vladimir Grushevsky
  description: Выкатка среды для разработки
  company: PAPALAM.RU

  license: MIT

  min_ansible_version: "2.1"

  platforms:
    - name: Ubuntu
      versions:
        - "all"
    - name: Debian
      versions:
        - "all"

  galaxy_tags: []

dependencies: []