---
- name: Установка pip
  ansible.builtin.apt:
    name: python3-pip
    state: present
    update_cache: yes
    cache_valid_time: 86400
  when: ansible_facts.os_family == "Debian"

- name: Установка pip пакетов
  ansible.builtin.pip:
    name:
      - docker
